language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: DbHCqv0ba9GSbdwA1HOU2bMkO0pxxVB0GT91+0McEtoQd7GAghnAcUyWS5fgyroNIaXoELVUWpwVMAzTRkbbZ1AlTYMpwXW98FGkAJCJ79vt7isp5jOuVHmTER60K5LeAN7FbLnSa0tPC3hvG0bcsm3XZqlNcNaDn9/Lf3z9xf3UEZ9hov1yjG/nv+IFcnx+KBeZ9tGprSoxQXKot6/wglEyFaPWzGF+xyQfJuFLxZu5DuK1zkMsaSrS2xZgrnzaPESrTT0Do/IkdzGZ/yxaF6P65D5i0xZrI/vuxmNW8iZOcPxhEsLoaU3eVSYZw2T4BvSQ+iufOIVh62tB4ZqUlasLBJIc0cndlEFByNGkYD26ECZjBSOj0CN4XS0cRilAPLk7Q4j9r6J9046fnqYA/IaUfHlOUif6uRqsP/EUVwdj81z+MzCKMfZyw8jewGJLjwQP63EFDn9e3YDNvDEjR5eVBQCZIXZ02AhyAeZ5g41CLJjpqC78dcxAXj/viKqe5CNTFVbd9pfAddE1adt9C+Lp/Cfau3/VT0kDq+mkjwQOJfJ4zZaQHnGBBhXr02K0j4JWwxOg1RZjga0jUWT2ei+UvedTwtAjq9WiZJiB0A25OyYdNxjIm8k3jskfPZDNenJv0to0R4ZoDcA6bxU2R1wEfr1KhH31J70xWzNF624=
