language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: QCBgf1SOMtraEUwVI+4pfyIiFM1qMso01CdA9rNInuJJvp9muVeS+Zdoi3li04p+APA4NaLMUitIb0Jd6Rhx0nXm/KnyhExetrElqlcKgvP45mkHuNw1qgmY6hMwojsVZnkHH27AG4eHFonode37FauDr8qitY3cF/+vVmrLcgvh1dBM61iB0pgnFGAU1zk/kTaWwyaJ6GCteGkiMIdNA24UBvaKr7QL4OtQAV5AfPmy2rRMrqLNW/iZIuwwzsN+4p0f87HhqR1dw6EJzqIXu0/aX0HRbmLuBF0rlF7DYNMPbpfN8CIf9PUfLcHdB3mjWzny4nrRdD6wxrLGMNchQ8btN9518Dndh3ac/Auax5yeMYAUWhh7MaCqpF558ndDlB5bgBAkHIA2cqSuw9I5DCzDVYaAnBE2XH5TMomnQhI4LQp/DdlT68zZERKN10XX8Tn/pWnnCmsr0AUsrkMKKsxztxf2aCuDFkw3dR7NIBt2S1FyeNvITTuSRpwFtV4wcz1nHgN07bJi2mIPYZD8/rrLFa8TlfQtLxB/8Okml8rKQ4PXLS9f/E/LCscHYrYjE+7f3+uDxTr9XJd7uJIwTre87K3MVhNNqpiy9sF8qlivYFCR4yvXzEMVjoZ/3XaohEhe3L3gZ6Vo4DMGJkA10KMwForWGvpyCtd6nghM+UI=
