language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: iab8JA33brBFIAvkRUEEjbZYe2oaDBBfQ9jMinvGoC2XmwqmcxZ1WGkhB0Fc3aeA61zdd6yyuJnf1u/rHX9fBL9bUDqJk8I031dMWSxcifAuCUM+QDaj2rdkkPukEDroj20mAWKzHOpDiNO5EyeRwbZlAu5a81lS+2ucqa+j60hZDSZWzi75LDM6TqGWdpOFgbcXzXuZERd5Y0uBQbu7IedxHgYGl7SvDrMeRpkdIcLqXNPxWd3n37S0PGyu8jGA7br5WGAhIX4IENGeY2aLUE6Yzaj3bcQbDHdSoz8w4nMsWzUTUGadbWJwTaa1mP8bfXrdklghDO9bLeUq4HKYLPk68dUThpwMhi4r/AECra6hnuRR+y6UTqQglFF7lhsIoK5eV3QoH4ur0TyLtnYz/S9tFOtbMKZ+AW8dk+5kkfh91v2hCFcguq4xBlFJCxmeCXEJ3812kIgdAXk8x6xjkZ8Jtom1fW2QNhWj2a217hguMUW6BZmCWEf+vDK+rtuGZO5F+UWvJB/cyIkEgv7lHX+99HgVjAu5aZnsTrtWbZ9OrUOw6ZPTWr6oKtReBWSPXk9Q2YaNDUwL08XyxYsPwRXLfNDPlM50MD+zbjsjp8rUSQweT1Eb08jc1zf5wrD6LExwOxOHYogBB4NgJz9FdhBIOD1UF33qhk4HicQ/xys=
