language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: CoJYDN0D1XE05HMczG3qjHiR8SKTaiuLN4/rwvJ9X3TFvRNx7grBQw9yd/IkrjKAlZ6XO9WD0z185GKTKZWAmSUsRLTnPFkhjd1N+WxupFTsR35bqLiUnAGQnAkIZLbxOraWYVB3P+Y33gVoiWuYaMDbYeiLuULVmmRkcii3cTj49is4CNOvYaNYmCa89rc9iyzcm2P/R/PT1CNqb5ecTfGiywXTwj3L14QkXSkSg+u9wCveqElxJiomz4XmHkN7NgSwwUDFEUriSAI2SesqRuLSdr8deEUUOl1G6iNPyEtSFpQ574Rn9YxVPCIqx614zABSvq0lDQ0D4mvsjyh+VetSIWgYK0sHGoe2c2NbQ1Q/b+LSaPmso8iU3BsSk1E4MAT7+zHOvp8OKNYMjyXI0JXMbIWCCPWODLCcfqogB+BbYO77Kd0u53SBBb8cio1q7frpnkC7Iv8u2IS4G5n8pdBucy4GRTW8rGHzZQLqtUtd4owEkvJpkYaLmrzWCVPLztZzlYFiB8X64fOZhsvyuJ4OtpjrgsiwFlgEpRNXrS1r2ph9P5lWPnZX9Jg+m5pzYTHttUKGT3Rg8Tc2oUavGG/DmfsdIuAWJzRJLo7rAqVcGAU0KsRUxOW47BQOyIE3hsbSQzROPqkdlBFxZ0YRo3bWAeoLssJn/KPNEOYtqM4=
