language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: G1MBtmuEFUGCP4mfsynJq8ySqxdB+n9zL34DumE4Qe9PeWmColEDTEWKuxuWK/CBTnb3yrADT8OEFm8CimFC950i5BwyVePPU6OF05YXu1PckPU/nB+xyPRD9FWFyHkFfDyt0VaoM2J8YOi9FeONeCW3+vIhVgTvqhk6EncJ5GlZpu02K87vZHpjXd8SLm2l7MbZH74IMxGe60hbJ6F2nCobNGPlogYYXNM0k9EDffLn/gE+vdQeH9zyVEWQEmmleUqyuV4+UtjROf3LkHIkroHDFjbvoIbwEZHZbOPnbUYFf4yyHOIswJpm4cuxgb4j0idXXS5BNzrQZR6ZFvkAzKf8D1kV5VJQENVvcjPVVtwxQFl8FgiO5q5+U14rfaAoxWZAM0PH2oU9ahs/vE+fVjZob2u/OwWLsUASDqvnwKO++mIm/0awV2nlOnR4WnF98cOk7sjNp/nfiov4t9AJnGl1CyBEZWZT/Wk7cOh6n1DgZvyPJbn/DjB/IQJs71HqtbQLTWX+yZZBah9nMpEEkQBHXhiIV0e9ldvMgayoRBinqZiCsl39URi8rS/FQtznlmzSSLYOq3otspcS9uCzlrkDewcJSn45DJ3+MOTITRoPCAkscQlnyg8/q5c1RbexRorGogPXp0DeX+epZA9gRpbhbFj31V/N2ZxHV4328YQ=
