language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: r/GRy9l/Y/zZqd/UPNPoYcq3bTZLlBKJLTNLQ1G0KH3l8lF1OeP8KekPQPe/buwZ7PpyxsohPfzJn97XaPcwS6W4sV9Bsyj/r2em2o9WUfvBiN5ZMX/cuHE3re1CgDo7dTeSUwGJkbNz4INm0OLLtKwsecUVCGViYsakcLNwhH86gMn2IKtFE9hE3Yci/07Ldb9Y1lKfJYEL/NHtK/VRHNQto0hM47iF4/VUWkEtY87gZ0Wb0FoTAd8AiEMhW52+Lsw9dC2ahqCwG0BHehUHV+m1E7ij4p6A5kPog+Ir82XdBqSzDo1NYojqL0TR3ySwqM4mANuHR5Y91clx4ZfN+RABiTm+eMHv1PRHfIzqHiR8kG6OWyhJcCbcIBaw2xBszbtvAYeTY4Uxxqr965nnyKdfGmt6sMlojhbMEk90KMi3eSJ4Ps5rQWkxzNGIUyu5K/Nkp2zA5ZHVbEXZ2uTd09aJv6AAJGww4Q/7dd3ZDBtwWsB9GR3JJtHLAlrjVZKUp/5UAZICDORYyxnLlEd0K2jYX5WZBOVgYwhYST2qxkultCkYtmqcZHjl7K+6YnXHGVwtOqNA7ZXTtoN8KGAPFKi8hoArrzpKQ8NyXuJJYKe/qgh8KpPP2EVgJgjFoj1mNvvBLbr4jpeUPibNMKXTIy78P8eqk4qv4q81/D6mIrI=
