language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  on:
    branch: master
  app: hidden-plains-84544
  api_key:
    secure: cQ1cQ0KrwKMk0o5f7tpZhkN7QPVbZ9IEvxbNUloUFCZgPwvq//7HEE9Khww+idftJf79bPKVaVPFV0JyLDCpC3zoUwrNtzWM92JBFDGxmijbAEcrBr1YS4591m/7YqlcCg6Nnkp6IlySzW5IwYAEBlQsgmOEgMWMBWM3ej7ohJGalatYf2Hg9Bmsn1EhM2785Tq9w59yS8SCyuBI2aDd8pMZL0LRDb4SZv9BQdqQz/OlgTPwA9p2t/xlPDHf/jHGAjHQ3edb+J+ebvQmnR5wHg+BhSaHelMPlMAfGuJEBfiSmGBuiQZC4a+jHjvpDMSxDH2hGbt1Vbp1VB20+NydsHcb2RZVBhAkACmDgwu+1pSsk1jDTQv5/Y2ZI52TgOU0F2cNA18ou0GHBmiOu1amlAKWM9KvIccUi/cRHYqZ5n63efpXvBsTbc2q6tsuLPUDye4f6ezDzOyYoVoEmcq0XxVAeeAquwoxf8qKD1CbpusCajH3S0/FhXT15oN2b1VmOdz1Hjhi1U0iuU5Ek0+tLdszGHas7V5n9W1NuJNebf3uVK1wNRYD0oGoecv5fVntC1S+rJ7SWCfB+72TPW+hV2gu8dJxgOG0uYMj/96UBTxGbq3bpn9Hj7v/2NhEa/5anzNl32IlOz8ZUODlOFJ57Cjvou33RvdIOIOhsPA1pdE=
